name: Playwright Tests and Report Deploy

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Ь Checkout reposit贸rio
        uses: actions/checkout@v3

      - name: 锔 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name:  Instalar depend锚ncias
        run: npm install

      - name: И Executar testes com Playwright
        run: npx playwright test

      - name:  Upload do relat贸rio HTML
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report
          retention-days: 7

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name:  Checkout do c贸digo
        uses: actions/checkout@v3

      - name:  Baixar relat贸rio como artefato
        uses: actions/download-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report

      - name:  Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
